/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_RNG */

#ifndef _Included_java_RNG
#define _Included_java_RNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_RNG
 * Method:    learn
 * Signature: ([Ljava/RNG;)V
 */
JNIEXPORT void JNICALL Java_java_RNG_learn
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
