/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Carro */

#ifndef _Included_Carro
#define _Included_Carro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Carro
 * Method:    update
 * Signature: (LCarro;LCarro;)V
 */
JNIEXPORT void JNICALL Java_Carro_update
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
