/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RNG */

#ifndef _Included_RNG
#define _Included_RNG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RNG
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_RNG_init
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
